Introduce validate-tas script to verify TS before committing

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -38,6 +38,21 @@ function js_tests() {
 }
 js_tests &
 
+function validate_ts() {
+    echo "${YELLOW}[pre-commit]${BLUE} Validating TS definitions... ${WHITE}"
+
+    OUTPUT=$(yarn run validate-ts 2>&1)
+     if [[ $? != 0 ]]; then
+        echo
+        echo "${BLUE}TS validation failed. Fix the error before commit!"
+        echo "${RED}$OUTPUT"
+        exit_reset_colors
+    fi
+    echo "${YELLOW}[pre-commit]${GREEN} TS validation Passed!${WHITE}"
+
+}
+validate_ts &
+
 # Go through each background task
 # If it sent exit code 1, it failed and the result from `wait` will be false.
 FAIL=0
